Разметка внутренней страницы
htmlacademy-htmlcss/2012749-device-33 pull request #2
Opened 2022-02-22 14:27 UTC by lilgikki

Главная страница

---
:mortar_board: [Разметка главной страницы](https://up.htmlacademy.ru/htmlcss/33/user/2012749/tasks/3)

---
:mortar_board: [Разметка внутренней страницы](https://up.htmlacademy.ru/htmlcss/33/user/2012749/tasks/4)

2022-02-22 16:40 UTC, lilgikki commented
Я впервые пользуюсь гитхабом, поэтому не уверена, что все верно отправила. Я отправила на проверку разметку главной и внутренней страницы (соответственно практика по 2.34 и 2.35)

2022-02-23 22:39 UTC, lilgikki commented
Сделала правки разметки

2022-02-24 14:59 UTC, Pakistanka requested changes
Все отлично) Поправь моменты с ссылками/кнопками и двигайся дальше

2022-02-24 14:59 UTC, Pakistanka commented on index.html
> +        <a href="#" class="button">Напишите нам</a>
Так не стоит делать: у ссылки не должно быть класса button, как и у button не должно быть класса, указывающего на ссылку

2022-02-24 14:59 UTC, Pakistanka commented on catalog.html
> +            <a class="navigation-link button" href="catalog.htnl">Каталог товаров</a>
Так не стоит делать: у ссылки не должно быть класса button, как и у button не должно быть класса, указывающего на ссылку

Нужно поправить по всей разметке

2022-02-24 14:59 UTC, Pakistanka commented on index.html
> +          <a class="link-item button" href="#">Подробнее</a>
Так не стоит делать: у ссылки не должно быть класса button, как и у button не должно быть класса, указывающего на ссылку

2022-02-25 20:23 UTC, merged